'use client';
import {useEffect,useRef,useState} from 'react';
import {supa,today,fmtDate} from '../lib/supabase';
import {shiftDate} from '../lib/phase2-data.mjs';
import {commuteValues} from '../lib/logging.mjs';

export default function Commute({userId,onOpen}){
 const [legs,setLegs]=useState([]),[week,setWeek]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const start=shiftDate(today(),-((new Date().getDay()+6)%7));
 useEffect(()=>{let alive=true;(async()=>{const results=await Promise.all([supa().from('runs').select('*').eq('user_id',userId).eq('date',today()).not('commute_direction','is',null).order('created_at'),supa().from('v_commute_weekly').select('*').eq('user_id',userId).eq('week_start',start).maybeSingle()]);for(const r of results)if(r.error)throw r.error;if(alive){setLegs(results[0].data||[]);setWeek(results[1].data);}})().catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[userId,start]);
 return <section className="card commute-card" aria-label="Commute"><div className="row"><strong>Commute</strong><small>{loading?'Loading…':error?'Totals unavailable':`${week?.days_cycled||0} commute days · ${week?.total_km||0} km this week`}</small></div>{error&&<p role="alert">{error}</p>}<div className="grid2">{['to_work','to_home'].map(dir=><button className="btn ghost" key={dir} onClick={()=>onOpen?.({direction:dir})}>{dir==='to_work'?'→ To work':'← Home'}</button>)}</div>{legs.map(l=><button className="food-result" key={l.id} onClick={()=>onOpen?.({direction:l.commute_direction,leg:l})}><strong>{l.commute_direction==='to_work'?'To work':'Home'} · {l.run_type==='cycle'?'Bike':l.run_type==='walk'?'Walk':'Run'}</strong><small>{l.distance_km??'—'} km · {l.duration_min??'—'} min · Edit</small></button>)}<p className="muted">Enter distance and time, then save.</p></section>;
}

export function CommuteLog({userId,direction,leg,onClose,onChanged}){
 const [form,setForm]=useState(()=>({duration_min:leg?.duration_min??'',distance_km:leg?.distance_km??'',rpe:leg?.rpe??'',carried_load_kg:leg?.carried_load_kg??'',hr_avg:leg?.hr_avg??'',hr_max:leg?.hr_max??'',notes:leg?.notes||''}));
 const [mode,setMode]=useState(leg?.run_type||'cycle'),[date,setDate]=useState(leg?.date||today()),[last,setLast]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState(false);
 const lock=useRef(false),id=useRef(leg?.id||null);
 useEffect(()=>{let alive=true;supa().from('runs').select('*').eq('user_id',userId).eq('commute_direction',direction).eq('run_type',mode).order('date',{ascending:false}).order('created_at',{ascending:false}).limit(20).then(r=>{if(!alive)return;if(r.error)setError(`Could not load previous trip: ${r.error.message}`);else setLast((r.data||[]).find(x=>x.id!==leg?.id&&x.date<=date)||null);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[userId,direction,mode,leg?.id,date]);
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(!date||date>today())throw new Error('Choose today or an earlier date.');const values=commuteValues(form);id.current ||= crypto.randomUUID();const r=await supa().from('runs').upsert({id:id.current,user_id:userId,date,run_type:mode,commute_direction:direction,...values},{onConflict:'id'}).select('id').single();if(r.error)throw r.error;onChanged?.();onClose();}catch(e){setError(`Not saved: ${e.message}`);}finally{lock.current=false;setBusy(false);}}
 async function deleteTrip(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await supa().from('runs').delete().eq('id',leg.id).eq('user_id',userId).select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('Trip unavailable. Reopen Commute.');onChanged?.();onClose();}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}
 return <div className="wrap logging-screen commute-screen"><div className="row"><h1>Commute {direction==='to_work'?'→ work':'→ home'}</h1><button className="btn ghost compact" disabled={busy} onClick={onClose}>‹ Back</button></div><p className="sub">{leg?'Edit trip':'New trip · saved only when you confirm'}</p>{error&&<div className="flag" role="alert">{error}</div>}<fieldset disabled={busy}><label>Date<input type="date" max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label><div className="seg" aria-label="Commute mode">{[['easy','Run'],['cycle','Bike'],['walk','Walk']].map(([value,label])=><button key={value} className={mode===value?'on':''} onClick={()=>setMode(value)}>{label}</button>)}</div><div className="grid2">{[['distance_km','Distance (km)'],['duration_min','Duration (min)']].map(([k,label])=><label key={k}>{label}<input inputMode="decimal" value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}</div>
 {last&&<button className="btn ghost" onClick={()=>setForm(f=>({...f,distance_km:last.distance_km??'',duration_min:last.duration_min??''}))}>Reuse {fmtDate(last.date)} · {last.distance_km??'—'} km in {last.duration_min??'—'} min</button>}
 <label>Effort · RPE 1–10 (optional)<input inputMode="numeric" value={form.rpe} onChange={e=>setForm(f=>({...f,rpe:e.target.value}))}/></label><div className="grid2">{[['carried_load_kg','Backpack (kg), optional'],['hr_avg','Average HR, optional'],['hr_max','Maximum HR, optional']].map(([k,label])=><label key={k}>{label}<input inputMode="decimal" value={form[k]} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}</div><label>Notes<textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label>
 <button className="btn" onClick={save}>{busy?'Saving…':leg?'Update trip':'Save trip'}</button>{leg&&(remove?<div className="row"><button className="btn ghost" onClick={deleteTrip}>Confirm delete trip</button><button className="btn ghost" onClick={()=>setRemove(false)}>Keep trip</button></div>:<button className="btn ghost" onClick={()=>setRemove(true)}>Delete trip</button>)}</fieldset></div>;
}
