'use client';
import {useEffect,useRef,useState} from 'react';
import {supa,BUILD} from '../lib/supabase';
import {DEFAULT_SETTINGS,SETTINGS_GROUPS,validateSettings} from '../lib/settings.mjs';
export default function Settings({user,onSaved,onWorkout,onExport,onLogs,onPain}){
 const [form,setForm]=useState(null),[days,setDays]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);const lock=useRef(false);
 useEffect(()=>{let alive=true;setForm(null);setError('');(async()=>{const [s,d]=await Promise.all([supa().from('user_settings').select('*').eq('user_id',user.id).maybeSingle(),supa().from('workout_days').select('*').eq('user_id',user.id).eq('is_active',true).order('sort_order')]);if(s.error||d.error)throw s.error||d.error;if(alive){setForm({...DEFAULT_SETTINGS,...s.data});setDays((d.data||[]).filter(x=>!x.is_daily));}})().catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[user.id,retry]);
 async function save(){if(lock.current||!form)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const values=validateSettings(form);const r=await supa().from('user_settings').upsert({user_id:user.id,...values},{onConflict:'user_id'}).select('*').single();if(r.error)throw r.error;setForm({...DEFAULT_SETTINGS,...r.data});setMessage('Settings saved across your devices.');onSaved(r.data);}catch(e){setError(`Not saved: ${e.message}`);}finally{lock.current=false;setBusy(false);}}
 return <div className="wrap logging-screen settings-screen"><h1>Settings</h1><p className="sub">Your programme & preferences</p><div className="card account-card"><span className="avatar">{user.email?.slice(0,2).toUpperCase()}</span><span><strong>{user.email}</strong><small>Signed in · changes sync across devices</small></span></div>{error&&<div className="flag" role="alert">{error}{!form&&<button className="btn ghost" onClick={()=>setRetry(x=>x+1)}>Retry</button>}</div>}{message&&<p role="status">{message}</p>}{!form&&!error&&<p>Loading settings…</p>}{form&&<fieldset disabled={busy}>{SETTINGS_GROUPS.map(([name,fields])=><section className="card settings-group" key={name}><h2>{name}</h2><div className="settings-rows">{fields.filter(([key])=>!['hr_target_high','threshold_high'].includes(key)).map(([key,label])=>{const upper=key==='hr_target_low'?'hr_target_high':key==='threshold_low'?'threshold_high':null;return <label key={key}>{upper?label.split(' · ')[0]:label}<span className={upper?'settings-band':'settings-value'}><input aria-label={label} inputMode="numeric" value={form[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/>{upper&&<>–<input aria-label={label.replace('lower','upper')} inputMode="numeric" value={form[upper]} onChange={e=>setForm(f=>({...f,[upper]:e.target.value}))}/></>}</span></label>;})}</div></section>)}<details className="card settings-race"><summary>Race · {form.race_name}</summary><label>Race name<input value={form.race_name} onChange={e=>setForm(f=>({...f,race_name:e.target.value}))}/></label><label>Race date<input type="date" value={form.race_date} onChange={e=>setForm(f=>({...f,race_date:e.target.value}))}/></label></details><p className="muted">These are your default targets. Existing run prescriptions keep their own HR bands; changing settings does not rewrite your programme.</p><label className="check-label"><input type="checkbox" checked={form.beep_enabled} onChange={e=>setForm(f=>({...f,beep_enabled:e.target.checked}))}/> Timer beeps</label><p className="muted">Metric units · week starts Monday</p><button className="btn" onClick={save}>{busy?'Saving…':'Save settings'}</button></fieldset>}
 <h2>Workouts</h2>{days.map(d=><button className="food-result" key={d.id} onClick={()=>onWorkout(d)}><strong>{d.name}</strong><small>Edit sets, order, enabled exercises or swap an exercise →</small></button>)}<div className="card"><button className="btn ghost" onClick={onPain}>Pain log</button><button className="btn ghost" onClick={onLogs}>All logs · run, body & photos</button><button className="btn ghost" onClick={onExport}>Export training data</button></div><button className="btn ghost danger" onClick={async()=>{if(!confirm('Sign out on this device?'))return;const r=await supa().auth.signOut();if(r.error)setError(r.error.message);}}>Sign out</button><p className="build-label">{BUILD}</p></div>;
}
